(and #t #t)
(and #t #f)
(and #f #t)
(and #f #f)
(and (or #t #f) (and #t #f))
(and #t #t #t #t #f)
(or #t #t)
(or #t #f)
(or #f #t)
(or #f #f)
(and #f #f #f #f #t)
(or (and #t #f) (or #t #f))
(not #t)
(not #f)
(not (not #f))
(not (and #t #f))
